### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "username": "user",
  "password": "BERSATU KITA TEGUH BERCERAI KITA RUNTUH 71264",
  "email": "CALONMPK17@gmail.com"
}

### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "CALONMPK17@gmail.com",
  "password": "BERSATU KITA TEGUH BERCERAI KITA RUNTUH 71264"
}


### CRUD
### Upload File
POST http://localhost:5000/api/files/upload
Content-Type: application/json

{
  "name": "Sample File",
  "link": "https://drive.google.com/file/d/1LZ8uIUTEn8c7l354Sb6IsanvPmrd5Ihd/view?usp=sharing"
}

### Get All Files
GET http://localhost:5000/api/files

### Download File
GET http://localhost:5000/api/download/{{fileId}}

### Delete File
DELETE http://localhost:5000/api/files/{{fileId}}


### Admin
### Register Admin
POST http://localhost:5000/api/admin/Adminregister
Content-Type: application/json

{
  "username": "ADMIN MPK SMKN 26 JAKARTA",
  "password": "SAHITYA ANANTA MPK 26 JAKARTA",
  "email": "AdminMPK26Jakarta@gmail.com"
}

### Login Admin
POST http://localhost:5000/api/admin/Adminlogin
Content-Type: application/json

{
  "email": "AdminMPK26Jakarta@gmail.com",
  "password": "SAHITYA ANANTA MPK 26 JAKARTA"
}